version: '3.6'
services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: "php-fpm"
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        user: "1000:1000"
        volumes:
            - ./src:/var/www
            - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - gitlab_hooks_redmine_app-network

    webserver:
        image: nginx
        container_name: "nginx"
        restart: unless-stopped
        ports:
            - 8098:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./docker/var/log/nginx:/var/log/nginx
        depends_on:
            - php-fpm
        networks:
            - gitlab_hooks_redmine_app-network


networks:
    gitlab_hooks_redmine_app-network:
        external: true
