version: '3.6'

services:
    gitlab:
        image: gitlab/gitlab-ee:latest
        container_name: "gitlab"
        restart: always
        ports:
            - '8929:8929'
        volumes:
            - '/srv/gitlab/config:/etc/gitlab'
            - '/srv/gitlab/logs:/var/log/gitlab'
            - '/srv/gitlab/data:/var/opt/gitlab'
        environment:
            GITLAB_OMNIBUS_CONFIG:  |
                external_url 'http://localhost:8929/'
        networks:
            - gitlab_hooks_redmine_app-network


networks:
    gitlab_hooks_redmine_app-network:
        external: true